[tool.poetry]
name = "evaluation_system"
version = "0.1.0"
description = "This system is about showing the rankings of challengers in the Leaderboard. It is also for judges to evaluate the participants based on their performances."
authors = ["Jerome Brenzuela <jeromebrenzuela935@gmail.com>"]

requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask-login>=0.6.3",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "flask-wtf>=1.2.2",
    "sqlalchemy>=2.0.38",
    "werkzeug>=3.1.3",
    "python-dotenv>=1.0.1",
    "pandas>=2.2.3",
    "xlsxwriter>=3.2.2",
    "pdfkit>=1.0.0",
]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.2.5"
flask-sqlalchemy = "^3.0"
flask-login = "^0.6.2"
pandas = "^2.0"
pdfkit = "^1.0.0"
werkzeug = "^2.2.3"
sqlalchemy = "^2.0"
jinja2 = "^3.1"